In [1]:
import numpy as np

In [7]:
arr = np.random.randint(10,50,size=10)
print(arr)

[31 49 14 12 19 29 24 48 46 22]


In [22]:
# np.where(condition) ==> indices of that condition
np.where(arr>30)

(array([ 1,  2,  3,  4,  5,  7,  9, 10, 11, 12, 13, 15, 16, 17, 18, 19],
       dtype=int64),)

In [25]:
fruits = np.array(['apple','banana','kiwi','chiku','mango'])

In [26]:
fruits

array(['apple', 'banana', 'kiwi', 'chiku', 'mango'], dtype='<U6')

In [27]:
np.where('i' in fruits)

C:\Users\Anoop Raj\AppData\Local\Temp\ipykernel_17068\1949276183.py:1: DeprecationWarning: Calling nonzero on 0d arrays is deprecated, as it behaves surprisingly. Use `atleast_1d(cond).nonzero()` if the old behavior was intended. If the context of this warning is of the form `arr[nonzero(cond)]`, just use `arr[cond]`.
  np.where('i' in fruits)


(array([], dtype=int64),)

In [11]:
np.where(arr>30,arr*2,arr/2)

array([124.  , 196.  ,   3.5 ,   3.  ,   4.75,   7.25,   6.  , 192.  ,
       184.  ,   5.5 ])

In [15]:
np.where(arr>30,False,True)

array([False,  True, False, False,  True, False, False, False, False,
       False,  True, False, False,  True,  True, False, False,  True,
       False, False])

In [16]:
arr = np.random.randint(10,80,size=20)
print(arr)

[16 40 68 60 34 74 28 50 14 43 63 33 59 51 20 63 34 67 55 39]


In [17]:
np.where(arr>=50,'good',np.where(arr>=30,"average",'poor'))

array(['poor', 'average', 'good', 'good', 'average', 'good', 'poor',
       'good', 'poor', 'average', 'good', 'average', 'good', 'good',
       'poor', 'good', 'average', 'good', 'good', 'average'], dtype='<U7')

In [18]:
arr

array([16, 40, 68, 60, 34, 74, 28, 50, 14, 43, 63, 33, 59, 51, 20, 63, 34,
       67, 55, 39])

In [19]:
np.argmax(arr) # index of maximum value

5

In [20]:
arr[np.argmax(arr)]

74

In [21]:
arr[np.argmin(arr)]

14

In [28]:
np.mean(arr)

45.55

In [29]:
np.sum(arr)

911

In [31]:
np.median(arr)

46.5

In [32]:
arr1 = np.array([1,2,3])
arr2 = np.array([10,20,30])

In [33]:
arr1+arr2

array([11, 22, 33])

In [34]:
arr1*arr2

array([10, 40, 90])

In [35]:
arr1/arr2

array([0.1, 0.1, 0.1])

In [ ]:
np.matmul()