In [4]:
import numpy as np

In [6]:
arr1 = np.arange(1,5)

In [7]:
print(arr1)

[1 2 3 4]


In [8]:
arr1.shape

(4,)

In [10]:
arr1.ndim

1

In [11]:
arr1[2:]

array([3, 4])

In [12]:
arr1 = np.arange(1,11)

In [13]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
arr1[5]

6

In [15]:
arr2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [16]:
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [17]:
arr2.shape

(3, 4)

In [18]:
arr2.ndim

2

In [19]:
[[1,2,3,4],[5,6,7,8],[9,10,11,12]]

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [20]:
arr2[0]

array([1, 2, 3, 4])

In [21]:
arr2[0][2]

3

In [22]:
arr2[2][-1]

12

In [24]:
arr2[2,-1]

12

In [25]:
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [27]:
arr2[-2:,1:3]

array([[ 6,  7],
       [10, 11]])

In [29]:
# array[row_slicing,col_slicing]

In [30]:
arr2[:-2,2:1]

array([], shape=(1, 0), dtype=int32)

In [32]:
arr2[:2,-2:]

array([[3, 4],
       [7, 8]])

In [34]:
arr2[:,1:2]

array([[ 2],
       [ 6],
       [10]])

In [35]:
arr2[1:2,:-1]

array([[5, 6, 7]])

In [36]:
list3d = [[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[1,2,3,4],[5,6,7,8],[9,10,11,12]]]
arr3d = np.array(list3d)
print(arr3d)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [37]:
arr3d.shape

(2, 3, 4)

In [38]:
arr3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [39]:
arr3d[:1,-2:,-2:]

array([[[ 7,  8],
        [11, 12]]])